/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { HubPostSummary } from "./util/search";
export namespace Components {
    interface HubModerationAssistant {
        /**
          * Discussion channel
         */
        "channelId": string;
        "entityId": string;
    }
    interface HubModerationFilters {
    }
    interface HubPostCard {
        "post": any;
    }
    interface HubPostsResults {
        "posts": any[];
    }
    interface HubPostsSummary {
        "summary": HubPostSummary;
    }
}
export interface HubModerationFiltersCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHubModerationFiltersElement;
}
declare global {
    interface HTMLHubModerationAssistantElement extends Components.HubModerationAssistant, HTMLStencilElement {
    }
    var HTMLHubModerationAssistantElement: {
        prototype: HTMLHubModerationAssistantElement;
        new (): HTMLHubModerationAssistantElement;
    };
    interface HTMLHubModerationFiltersElement extends Components.HubModerationFilters, HTMLStencilElement {
    }
    var HTMLHubModerationFiltersElement: {
        prototype: HTMLHubModerationFiltersElement;
        new (): HTMLHubModerationFiltersElement;
    };
    interface HTMLHubPostCardElement extends Components.HubPostCard, HTMLStencilElement {
    }
    var HTMLHubPostCardElement: {
        prototype: HTMLHubPostCardElement;
        new (): HTMLHubPostCardElement;
    };
    interface HTMLHubPostsResultsElement extends Components.HubPostsResults, HTMLStencilElement {
    }
    var HTMLHubPostsResultsElement: {
        prototype: HTMLHubPostsResultsElement;
        new (): HTMLHubPostsResultsElement;
    };
    interface HTMLHubPostsSummaryElement extends Components.HubPostsSummary, HTMLStencilElement {
    }
    var HTMLHubPostsSummaryElement: {
        prototype: HTMLHubPostsSummaryElement;
        new (): HTMLHubPostsSummaryElement;
    };
    interface HTMLElementTagNameMap {
        "hub-moderation-assistant": HTMLHubModerationAssistantElement;
        "hub-moderation-filters": HTMLHubModerationFiltersElement;
        "hub-post-card": HTMLHubPostCardElement;
        "hub-posts-results": HTMLHubPostsResultsElement;
        "hub-posts-summary": HTMLHubPostsSummaryElement;
    }
}
declare namespace LocalJSX {
    interface HubModerationAssistant {
        /**
          * Discussion channel
         */
        "channelId"?: string;
        "entityId"?: string;
    }
    interface HubModerationFilters {
        "onFiltersChanged"?: (event: HubModerationFiltersCustomEvent<any>) => void;
    }
    interface HubPostCard {
        "post"?: any;
    }
    interface HubPostsResults {
        "posts"?: any[];
    }
    interface HubPostsSummary {
        "summary"?: HubPostSummary;
    }
    interface IntrinsicElements {
        "hub-moderation-assistant": HubModerationAssistant;
        "hub-moderation-filters": HubModerationFilters;
        "hub-post-card": HubPostCard;
        "hub-posts-results": HubPostsResults;
        "hub-posts-summary": HubPostsSummary;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hub-moderation-assistant": LocalJSX.HubModerationAssistant & JSXBase.HTMLAttributes<HTMLHubModerationAssistantElement>;
            "hub-moderation-filters": LocalJSX.HubModerationFilters & JSXBase.HTMLAttributes<HTMLHubModerationFiltersElement>;
            "hub-post-card": LocalJSX.HubPostCard & JSXBase.HTMLAttributes<HTMLHubPostCardElement>;
            "hub-posts-results": LocalJSX.HubPostsResults & JSXBase.HTMLAttributes<HTMLHubPostsResultsElement>;
            "hub-posts-summary": LocalJSX.HubPostsSummary & JSXBase.HTMLAttributes<HTMLHubPostsSummaryElement>;
        }
    }
}
